### ISSUE TITLE
Review current state of selection system

### ISSUE THREAD

**Issue by hechth** [tumcms/Open-Infra-Platform#25]
# Tasks
- [ ] Document all findings to create a guideline of how to implement selectable objects using the BlueFramework in OIP.
- [ ] Get familiar with the selection system by looking at the [ViewCube](https://github.com/tumcms/Blue-Framework/tree/master/Engine/src/BlueFramework/Engine/ViewCube) implementation.
- [ ] Inspect the ViewCube [shader](https://github.com/tumcms/Blue-Framework/blob/master/Engine/src/BlueFramework/Engine/ViewCube/Shader/D3D12/ViewCubeEffect.hlsl) and effect files to get familiar with the idea of render targets and the _pick buffer_.
- [ ] Browse the code in the BlueFramework [Rasterizer](https://github.com/tumcms/Blue-Framework/tree/master/Rasterizer/src/BlueFramework/Rasterizer) related to the IEffect and IRenderSystem classes and how they work (Effect.h, Resources/IEffectCore.h, IRenderSystem.h and the respective implementations in [D3D11](https://github.com/tumcms/Blue-Framework/tree/master/D3D11RenderSystem/src/BlueFramework/D3D11RenderSystem) or [D3D12](https://github.com/tumcms/Blue-Framework/tree/master/D3D12RenderSystem/src/BlueFramework/D3D12RenderSystem)).
- [ ] Get familiar with basic shader programming in HLSL for rendering on the GPU.
- [ ] Get familiar with the `PickIdGenerator` class and how to assign IDs to objects.
- [ ] Find out how the `pickID` of an object is passed to the GPU in the VertexBuffer.
- [ ] Evaluate which [vertex](https://github.com/tumcms/Blue-Framework/blob/master/Rasterizer/src/BlueFramework/Rasterizer/vertex.h) format is suitable for rendering IFC files with selection.
- [ ] Review written documentation and include in the OIP Documentation.
