### ISSUE TITLE
[REF] Unit tests' namespace

### ISSUE THREAD

**Issue by pjanck** [tumcms/Open-Infra-Platform#377]
**File which is being refactored**
All visual unit tests + their base classes + helpers.

Looking at the compiled doxymentation, all visual unit tests are missing their namespace.

**Tasks**

- [ ] Introduce a new namespace `UnitTesting` within the OIP namespace:

        namespace OpenInfraPlatform {
        namespace UnitTesting {
        ... }}

- [ ] Prepare a `namespace.h` with defines, similar to other projects.
- [ ] Update all visual unit tests.
